### ISSUE TITLE
Crash sur monde local !

### ISSUE THREAD

**Issue by Hibernus96** [Gogo08190/Chroma-Technology-2#1]
J'ai ouvert le portail du nether depuis je crash en boucle des que je relance !

Niveau matos j'ai un i9/RTX2070/64gb de ram a 3200mhz, du coup ca ne vient pas du manque de ressources !

https://gist.githubusercontent.com/natanfudge/d48f10cc60becb818ea37ce0df356e4d/raw/da4305be2a0592564db48524ac86a889206f7680/crash.txt

**Comment by Gogo08190** [comment]
Le soucis vient du mod sodium nous avons contacté le dev du mod. Certaines personnes ont le crash d'autre non il te suffit de retirer le mod sodium reforged pour corriger le bug
