### ISSUE TITLE
Some Ores not spawning in "Mining World" Dimension.

### ISSUE THREAD

**Issue by Koutsokou** [Gogo08190/Chroma-Technology-2#14]
I said in the title, some ores do not spawn in the mining dimension. I have not searched for every ore, but I have found that emerald and bauxite (aluminum) ore do not spawn. Is this intended?

**Comment by koepss** [comment]
Hello, yes this is intended, you must find those ores in the overworld.

**Comment by Koutsokou** [comment]
So is there a reason for the mining dimension if you have all the ores in the overworld?

**Comment by koepss** [comment]
so as not to break the world.
