### ISSUE TITLE
Silent gear weapons 

### ISSUE THREAD

**Issue by LordMy91** [Gogo08190/Chroma-Technology-2#16]
Hello, 
So I was creating a machete from silent gear. I used the dragon steel (Ice) for it. I supercharged, and graded the steel, also coated it. I made the machete, but I cannot use it on mobs. It goes through them instead of hitting them. I also used other materials to create the machete and it does work on mobs. 

I also made dragon steel armor with silent gear and does work, just the machete is not working. 

Can you help with this?

**Comment by koepss** [comment]
Good evening it's a problem of the mod we can not help you too much on that.
