### ISSUE TITLE
[Suggestion] MiniUtilities mod

### ISSUE THREAD

**Issue by maicol07** [Gogo08190/Chroma-Technology-2#18]
Hi,

it would be useful to have [Mini Utilities](https://www.curseforge.com/minecraft/mc-mods/miniutilities) in the pack to create mob farms.

Thanks!

**Comment by Gogo08190** [comment]
You can make mob farm with Dark Utilities

**Comment by maicol07** [comment]
@Gogo08190 yes, I know, but MiniUtilities has the Cursed Eaaarth that make mobs spawn way more frequently!

**Comment by Gogo08190** [comment]
You have the same with Dark Utilities

**Comment by Gogo08190** [comment]
https://youtu.be/3giO0XZDUpA

**Comment by maicol07** [comment]
Oh, didn't know that! Thanks!
