### ISSUE TITLE
maybe swap productive with resourceful bees.

### ISSUE THREAD

**Issue by KadenZangoose** [Gogo08190/Chroma-Technology-2#19]
I feel this bee mod would be better senses it adds more apiary's, it can be config, genetics, and addons for more tiers of centrifuges and creative apiary's.

[[Resourceful Bees](https://www.curseforge.com/minecraft/mc-mods/resourceful-bees)]

https://www.curseforge.com/minecraft/mc-mods/centrifuge-tiers

**Comment by koepss** [comment]
Good evening we will not change the bee mod for the simple reason that the bee mod that we have put in more bees and may affect genetics.
