### ISSUE TITLE
Infinite "waiting for server"

### ISSUE THREAD

**Issue by maicol07** [Gogo08190/Chroma-Technology-2#22]
Hi,

After some minutes I play I get "Waiting for server". Can you check what is wrong.

Here are the logs:
[latest.zip](https://github.com/Gogo08190/Chroma-Technology-2/files/7573258/latest.zip)
[debug.zip](https://github.com/Gogo08190/Chroma-Technology-2/files/7573255/debug.zip)

Thanks

**Comment by koepss** [comment]
Good evening you play with it Optifine?

**Comment by maicol07** [comment]
> Good evening you play with it Optifine?

Unfortunately yes, I'm playing with heavy resource packs and the only way I've found to have a good frame rate is with Optifine. Every other mod I've tried (RoadRunner, Sodium, Magnesium, ...) gave me 10-25 FPS.
I know Optifine is the primary cause of mods incompatibilities, but I've tried to avoid it... Although, I've failed...

**Comment by maicol07** [comment]
So I've managed to get it work with the same performances (sometimes better) with Magnesium + Sulfuric + RoadRunner and it seems working. I'll close this issue soon if it doesn't happen anymore
