### ISSUE TITLE
Replace `BetterEnd` with `BetterEnd Reforked`

### ISSUE THREAD

**Issue by maicol07** [Gogo08190/Chroma-Technology-2#24]
Currently, the first [BetterEnd port for Forge](https://www.curseforge.com/minecraft/mc-mods/betterend-forge-port) has been abandoned, and it is now maintained under the [BetterEnd Reforked](https://www.curseforge.com/minecraft/mc-mods/betterend-re-forked) name

**Comment by Gogo08190** [comment]
Je ferme le ticket car je travail sur la prochaine maj !
