### ISSUE TITLE
Wires for Redstone Flux Coils

### ISSUE THREAD

**Issue by Vercalos** [Gogo08190/Chroma-Technology-2#3]
Not sure if this is intended or not, but the **Redstone Flux Coil** for the _Thermal Series_' recipe doesn't use the Forge dictionary for the wires, so the **Gold Wire** from _Create Crafts & Additions_ one gets from sending a sheet through a _Rolling Machine_ works for the recipe, the **Copper Wire** from the same mod doesn't work, and you must use the **Copper Wire** from _Immersive Engineering_ instead.

**Comment by Gogo08190** [comment]
Hello,

It's voluntary to use as many mods as possible 😃

**Comment by Vercalos** [comment]
So it was intentional that the _Copper Wires_ were not interchangeable?

**Comment by Gogo08190** [comment]
Yes exactly

**Comment by Vercalos** [comment]
Alright then.
