### ISSUE TITLE
Adding Optifine G8 causes crash on start up

### ISSUE THREAD

**Issue by fborti** [Gogo08190/Chroma-Technology-2#30]
Hi,

I know Optifine is prone to causing crashes, I just wanted to know if there was any way to fix the crashing problem other than removing Optifine.

**Comment by koepss** [comment]
Hello optifine is not compatible with some mod present on the modpack.

**Comment by fborti** [comment]
I figured, are those core mods or can they be disabled? 
Do you know if there is anything similar to Optifine that is compatible with the pack?
Thanks!

**Comment by Gogo08190** [comment]
Halogen (sodium) is already on the modpack. It's better than Optifine
