### ISSUE TITLE
[BUG] Serious Frame drops and Unsure Why

### ISSUE THREAD

**Issue by FoxDogist** [Gogo08190/Chroma-Technology-2#33]
### Description of the Bug

For whatever reason, my friends and I have some serious frame drops in our base. We've already attempted to find the issue, whether it be Mekanism pipes or supplementary's peaceable entities (like enchanted books or sticks) but we're still having really bad issues. I personally go from about 170 to roughly 80

### Expected Behaviour

Ideally, we shouldn't be having frames drop at all. Or at least very little

### Modpack Version

1.16.5

**Comment by FoxDogist** [comment]
I will try and add more resources like screenshots when possible

**Comment by Gogo08190** [comment]
Fix in version 1.0.4
