### ISSUE TITLE
[BUG] *can't make pneumaticcraft compressed iron

### ISSUE THREAD

**Issue by MineCherry** [Gogo08190/Chroma-Technology-2#34]
### Description of the Bug

Explosion will not trigger the compressed iron Event with minecraft TNT. Iron will be destroyed.

Solution:
You can trigger the Event by using AE2 Tina tnt

### Expected Behaviour

1. Place vanilla TNT
2. Drop iron close to tnt
3. Trigger tnt
4. Iron is gone

### Modpack Version

1.2.1

**Comment by Gogo08190** [comment]
Read the quest and use tiny tnt.
