### ISSUE TITLE
[BUG] crash using optifine

### ISSUE THREAD

**Issue by Duckrender** [Gogo08190/Chroma-Technology-2#35]
### Description of the Bug

Whenever i try launching the game with optifine in mods folder it crashes at launch

### Expected Behaviour

idk what to put here

### Modpack Version

1.2.1

### Screenshots

![image](https://user-images.githubusercontent.com/105236611/167466489-bf992fc0-c862-4991-b7dc-3f1000b169cf.png)

**Comment by koepss** [comment]
Incompatible
