### ISSUE TITLE
Recipe: Bronze Gear craftable?

### ISSUE THREAD

**Issue by Vercalos** [Gogo08190/Chroma-Technology-2#4]
Given all the other Gear recipes are restricted to the **Metal Press** from _Immersive Engineering_, the **Casting Table** from _Tinkers' Construct_, and **Multiservo Press** from _Thermal Series_, I think that the fact that the **Bronze Gear** is craftable just using **Bronze Ingots** and an **Iron Nugget**, that you might have forgotten to disable that recipe.

**Comment by Gogo08190** [comment]
Fix in the next update ! Thanks you !
