### ISSUE TITLE
[Suggestion] FastWorkBench

### ISSUE THREAD

**Issue by jinkhya** [Gogo08190/Chroma-Technology-2#5]
Bonjour,
Est-ce qu'il serait possible d'ajouter le mod fastworkbench? il aide grandement à ne pas faire lagger le serveur quand on fait des gros crafts tels qu'un stack de redstone blocks (ou coal) par exemple.
https://www.curseforge.com/minecraft/mc-mods/fastworkbench

"This is a mod aimed at improving performance of all crafting-related functions.  It fixes the bug introduced in Minecraft 1.12 where shift-click crafting a stack of items could cause momentary freezes.  However, it does slightly more than just fixing that issue."

Merci d'avance ! 
Jin

**Comment by koepss** [comment]
Bonsoir je vais prendre note de cette demande et y réfléchir pour la prochaine maj.

**Comment by Gogo08190** [comment]
Je l'ajouterai lors de la prochaine mise à jour.
